name: "Test build with published image"

on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:
  workflow_call:

concurrency:
  group: actions_test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  actions_tagged:
    permissions: {}
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged
    strategy:
      matrix:
        variant:
          - arch: x86_64
            runner: ubuntu-24.04
          - arch: aarch64
            runner: ubuntu-24.04-arm
      fail-fast: false
    runs-on: ${{ matrix.variant.runner }}
    steps:
      - name: Clone the app
        run: |
          git clone --depth=1 --branch master --single-branch --recursive https://github.com/flathub/org.gnome.Sudoku.git
          cd org.gnome.Sudoku && rm -rf ".git"

      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          build-bundle: false
          upload-artifact: false
          cache: false
          restore-cache: false
          manifest-path: org.gnome.Sudoku/org.gnome.Sudoku.json
          arch: ${{ matrix.variant.arch }}
          verbose: true
          branch: stable
          mirror-screenshots-url: https://dl.flathub.org/media

      - name: Run linter
        run: |
          flatpak-builder-lint --exceptions manifest org.gnome.Sudoku/org.gnome.Sudoku.json
          flatpak-builder-lint --exceptions builddir flatpak_app
          flatpak-builder-lint --exceptions repo repo

  actions_master:
    permissions: {}
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged
    strategy:
      matrix:
        variant:
          - arch: x86_64
            runner: ubuntu-24.04
          - arch: aarch64
            runner: ubuntu-24.04-arm
      fail-fast: false
    runs-on: ${{ matrix.variant.runner }}
    steps:
      - name: Clone the app
        run: |
          git clone --depth=1 --branch master --single-branch --recursive https://github.com/flathub/org.gnome.Sudoku.git
          cd org.gnome.Sudoku && rm -rf ".git"

      - uses: flatpak/flatpak-github-actions/flatpak-builder@master
        with:
          build-bundle: false
          upload-artifact: false
          cache: false
          restore-cache: false
          manifest-path: org.gnome.Sudoku/org.gnome.Sudoku.json
          arch: ${{ matrix.variant.arch }}
          verbose: true
          branch: stable
          mirror-screenshots-url: https://dl.flathub.org/media

      - name: Run linter
        run: |
          flatpak-builder-lint --exceptions manifest org.gnome.Sudoku/org.gnome.Sudoku.json
          flatpak-builder-lint --exceptions builddir flatpak_app
          flatpak-builder-lint --exceptions repo repo
